version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/vue_project
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
